# Generated by Django 6.0.3 on 2026-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='application_process',
            field=models.TextField(blank=True, null=True),
        ),
    ]
