# Generated by Django 5.1.6 on 2026-03-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_governmentscheme_visits_alter_chatmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='level',
            field=models.CharField(choices=[('Central', 'Central'), ('State', 'State'), ('Gram Panchayat', 'Gram Panchayat')], default='Central', max_length=50),
        ),
    ]
