# Generated by Django 5.1.6 on 2026-03-24 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_passwordresettoken_delete_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.governmentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
